name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Discord Token Tag Replacement
        uses: AlexRogalskiy/github-action-tag-replacer@v2.0.1
        with:
          sourceFile: ./Dockerfile
          placeholder: DISCORD_TOKEN
          replacement: ${{ secrets.DISCORD_TOKEN }}
      
      - name: Discord Client Id Tag Replacer
        uses: AlexRogalskiy/github-action-tag-replacer@v2.0.1
        with:
          sourceFile: ./Dockerfile
          placeholder: DISCORD_CLIENT_ID
          replacement: ${{ secrets.DISCORD_CLIENT_ID }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: squidbot.azurecr.io
          username: ${{ secrets.SQUIDBOT_REGISTRY_USERNAME }}
          password: ${{ secrets.SQUIDBOT_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: squidbot.azurecr.io/squidbot:${{ github.sha }}
          file: ./Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SQUIDBOT_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n squidbot -g Squidbot --server squidbot.azurecr.io --username  ${{ secrets.SQUIDBOT_REGISTRY_USERNAME }} --password ${{ secrets.SQUIDBOT_REGISTRY_PASSWORD }}
            az containerapp update -n squidbot -g Squidbot --image squidbot.azurecr.io/squidbot:${{ github.sha }}