name: Trigger auto deployment for squidbot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'dockerfile/**'
    - '.github/workflows/squidbot-AutoDeployTrigger-6d18c429-71d2-4e1a-9b91-31985f5c7e2e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: squidbot.azurecr.io
          username: ${{ secrets.SQUIDBOT_REGISTRY_USERNAME }}
          password: ${{ secrets.SQUIDBOT_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: squidbot.azurecr.io/squidbot:${{ github.sha }}
          file: ./dockerfile/Dockerfile
          context: ./dockerfile/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SQUIDBOT_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n squidbot -g Squidbot --server squidbot.azurecr.io --username  ${{ secrets.SQUIDBOT_REGISTRY_USERNAME }} --password ${{ secrets.SQUIDBOT_REGISTRY_PASSWORD }}
            az containerapp update -n squidbot -g Squidbot --image squidbot.azurecr.io/squidbot:${{ github.sha }}
